'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import { ArrowRight,Check,HeartHandshake,MapPin,MessageCircle,UserPlus } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

export default function PersonClient({person,currentProfileId}:{person:any;currentProfileId:string}){
 const supabase=useMemo(()=>createClient(),[])
 const [directory,setDirectory]=useState<any>(null),[offers,setOffers]=useState<any[]>([]),[asks,setAsks]=useState<any[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{const [d,o,a]=await Promise.all([
  supabase.from('member_directory').select('display_name,photo_url,city_region,interests,skills,help_offers,communities,accepts_introductions,accepts_asks,availability_status,professional_capability,bio').eq('profile_id',person.id).maybeSingle(),
  supabase.from('offers').select('id,title,description,category,offer_type,status').eq('profile_id',person.id).in('status',['open','active']).limit(12),
  supabase.from('asks').select('id,title,description,category,ask_type,urgency,status').eq('profile_id',person.id).in('status',['open','active']).limit(12)
 ]);setDirectory(d.data);setOffers(o.data||[]);setAsks(a.data||[])},[person.id,supabase])
 useEffect(()=>{void load()},[load])
 async function connect(){if(currentProfileId===person.id)return;setBusy(true);setStatus('');const existing=await supabase.from('member_connections').select('id,status').or(`and(requester_profile_id.eq.${currentProfileId},addressee_profile_id.eq.${person.id}),and(requester_profile_id.eq.${person.id},addressee_profile_id.eq.${currentProfileId})`).maybeSingle();if(existing.data){setStatus(existing.data.status==='accepted'?'Already connected.':'A connection already exists.');setBusy(false);return}const c=await supabase.from('member_connections').insert({requester_profile_id:currentProfileId,addressee_profile_id:person.id,status:'pending',metadata:{source:'people_market'}}).select('id').single();if(c.error){setStatus(c.error.message);setBusy(false);return}const r=await supabase.from('connection_requests').insert({connection_id:c.data.id,requester_profile_id:currentProfileId,addressee_profile_id:person.id,status:'pending',note:'I found you through BeLoved and would like to connect.'});if(r.error){setStatus(r.error.message);setBusy(false);return}await supabase.from('notifications').insert({recipient_profile_id:person.id,actor_profile_id:currentProfileId,notification_type:'connection_request',title:'New BeLoved connection request',body:'Someone would like to connect with you.',metadata:{connection_id:c.data.id}});setStatus('Connection request sent.');setBusy(false)}
 async function startMessage(){setBusy(true);setStatus('');const c=await supabase.from('conversations').insert({created_by_profile_id:currentProfileId,subject:`Conversation with ${person.name||'BeLoved member'}`,context_type:'connection',status:'open'}).select('id').single();if(c.error){setStatus(c.error.message);setBusy(false);return}const p=await supabase.from('conversation_participants').insert([{conversation_id:c.data.id,profile_id:currentProfileId,status:'active'},{conversation_id:c.data.id,profile_id:person.id,status:'active'}]);if(p.error){setStatus(p.error.message);setBusy(false);return}window.location.href=`/messages?conversation=${c.data.id}`}
 return <div className="mx-auto max-w-6xl px-4 pb-24 sm:px-6 lg:px-8"><section className="grid gap-8 py-12 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-[2rem] bg-[#17364d] p-8 text-[#f7f4ed]">{person.avatar?<img src={person.avatar} alt="" className="h-24 w-24 rounded-full object-cover"/>:<div className="grid h-24 w-24 place-items-center rounded-full bg-white/10 text-3xl">{(person.name||'B').charAt(0)}</div>}<h1 className="mt-6 font-serif text-4xl font-light">{person.name||'BeLoved member'}</h1><p className="mt-3 flex items-center gap-2 text-sm opacity-55"><MapPin size={14}/>{person.location_text||directory?.city_region||'Local member'}</p><p className="mt-5 leading-7 opacity-65">{person.bio||directory?.bio||'A living profile in the BeLoved community.'}</p><div className="mt-7 flex flex-wrap gap-2"><button disabled={busy||currentProfileId===person.id} onClick={()=>void connect()} className="rounded-full bg-[#f7f4ed] px-5 py-3 text-sm text-[#17364d] disabled:opacity-40"><UserPlus className="mr-2 inline h-4 w-4"/>{currentProfileId===person.id?'This is you':'Connect'}</button><button disabled={busy||currentProfileId===person.id} onClick={()=>void startMessage()} className="rounded-full border border-white/20 px-5 py-3 text-sm disabled:opacity-40"><MessageCircle className="mr-2 inline h-4 w-4"/>Message</button></div>{status&&<p className="mt-4 text-sm opacity-70">{status}</p>}</div><div className="space-y-5"><section className="rounded-[2rem] bg-white p-7"><p className="text-[9px] uppercase tracking-[.28em] text-[#557060]">Human potential</p><h2 className="mt-3 font-serif text-3xl font-light">{directory?.professional_capability||'Capability'}</h2><div className="mt-5 flex flex-wrap gap-2">{[...(directory?.skills||[]),...(directory?.interests||[])].slice(0,12).map((x:string)=><span key={x} className="rounded-full bg-[#f7f4ed] px-3 py-2 text-xs">{x}</span>)}</div></section><div className="grid gap-5 md:grid-cols-2"><Card title="Offers" icon={<HeartHandshake/>} items={offers}/><Card title="Needs" icon={<Check/>} items={asks}/></div></div></section><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Link href="/market" className="rounded-3xl bg-white p-6">Back to People Market <ArrowRight className="mt-4 h-4 w-4"/></Link><Link href="/hey-neighbor" className="rounded-3xl bg-white p-6">Local needs <ArrowRight className="mt-4 h-4 w-4"/></Link><Link href="/network" className="rounded-3xl bg-white p-6">Relationships <ArrowRight className="mt-4 h-4 w-4"/></Link><Link href="/journey" className="rounded-3xl bg-white p-6">Journey <ArrowRight className="mt-4 h-4 w-4"/></Link></section></div>
}
function Card({title,icon,items}:{title:string;icon:React.ReactNode;items:any[]}){return <section className="rounded-[2rem] bg-white p-6"><div className="flex items-center gap-3 opacity-50">{icon}<h2 className="font-serif text-2xl font-light">{title}</h2></div><div className="mt-4 space-y-2">{items.slice(0,5).map(x=><div key={x.id} className="rounded-xl bg-[#f7f4ed] p-4"><p className="text-sm font-medium">{x.title}</p>{x.description&&<p className="mt-1 text-xs leading-5 opacity-55">{x.description}</p>}</div>)}{!items.length&&<p className="text-sm opacity-45">Nothing active here yet.</p>}</div></section>}
