'use client'
import { useCallback,useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import { ArrowRight,HeartHandshake,RefreshCw,Users } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Item={id:string;profile_id:string|null;provider:string|null;external_url:string|null;author_name:string|null;title:string|null;body:string|null;excerpt:string|null;content_type:string|null;published_at:string|null;created_at:string}
type Signal={id:string;kind:'social'|'ask'|'offer'|'opportunity';title:string;body:string|null;date:string;profile_id?:string|null;url?:string|null}

export default function SocialClient(){
 const supabase=useMemo(()=>createClient(),[])
 const [items,setItems]=useState<Signal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 const load=useCallback(async()=>{setLoading(true);setError('');const [s,a,o,p]=await Promise.all([
  supabase.from('social_feed_items').select('id,profile_id,provider,external_url,author_name,title,body,excerpt,content_type,published_at,created_at').order('published_at',{ascending:false}).limit(40),
  supabase.from('asks').select('id,profile_id,title,description,created_at').in('status',['open','active']).order('created_at',{ascending:false}).limit(20),
  supabase.from('offers').select('id,profile_id,title,description,created_at').in('status',['open','active']).order('created_at',{ascending:false}).limit(20),
  supabase.from('opportunities').select('id,title,description,type,created_at').eq('status','active').order('created_at',{ascending:false}).limit(20)
 ]);const e=[s.error,a.error,o.error,p.error].find(Boolean);if(e)setError(e.message);const merged:Signal[]=[...((s.data||[]) as Item[]).map(x=>({id:x.id,kind:'social' as const,title:x.title||x.author_name||x.provider||'Community signal',body:x.body||x.excerpt,date:x.published_at||x.created_at,profile_id:x.profile_id,url:x.external_url})),...((a.data||[]) as any[]).map(x=>({id:x.id,kind:'ask' as const,title:x.title,body:x.description,date:x.created_at,profile_id:x.profile_id})),...((o.data||[]) as any[]).map(x=>({id:x.id,kind:'offer' as const,title:x.title,body:x.description,date:x.created_at,profile_id:x.profile_id})),...((p.data||[]) as any[]).map(x=>({id:x.id,kind:'opportunity' as const,title:x.title,body:x.description,date:x.created_at}))];merged.sort((x,y)=>+new Date(y.date)-+new Date(x.date));setItems(merged);setLoading(false)},[supabase])
 useEffect(()=>{void load()},[load])
 if(loading)return <div className="mx-auto grid min-h-[60vh] place-items-center"><RefreshCw className="animate-spin"/></div>
 return <div className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8"><section className="flex items-end justify-between gap-5 py-12"><div><p className="text-[9px] uppercase tracking-[.3em] text-[#557060]">Community nervous system</p><h1 className="mt-3 font-serif text-5xl font-light">Notice what is happening. Then act.</h1><p className="mt-5 max-w-2xl leading-7 opacity-60">Social activity, needs, offers, and opportunities become signals that can lead to relationships and real-world action.</p></div><button onClick={()=>void load()} className="rounded-full border border-[#17364d]/10 bg-white px-4 py-2 text-sm"><RefreshCw className="mr-2 inline h-4 w-4"/>Refresh</button></section>{error&&<div className="mb-5 rounded-2xl bg-white p-4 text-sm">{error}</div>}<div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><section className="space-y-4">{items.map(item=><article key={`${item.kind}-${item.id}`} className="rounded-[2rem] bg-white p-6"><div className="flex items-center justify-between gap-3"><span className="text-[9px] uppercase tracking-[.25em] text-[#557060]">{item.kind}</span><span className="text-[10px] opacity-35">{new Date(item.date).toLocaleString()}</span></div><h2 className="mt-3 font-serif text-2xl font-light">{item.title}</h2>{item.body&&<p className="mt-3 leading-7 opacity-60">{item.body}</p>}<div className="mt-5 flex flex-wrap gap-2">{item.profile_id&&<Link href={`/people/${item.profile_id}`} className="rounded-full border border-[#17364d]/10 px-4 py-2 text-xs">Open person <ArrowRight className="ml-1 inline h-3 w-3"/></Link>}{item.kind==='social'&&item.url&&<a href={item.url} target="_blank" rel="noreferrer" className="rounded-full border border-[#17364d]/10 px-4 py-2 text-xs">Open source</a>}{item.kind!=='social'&&<Link href={item.kind==='ask'?'/hey-neighbor':'/market'} className="rounded-full bg-[#17364d] px-4 py-2 text-xs text-white">Take action</Link>}</div></article>)}{!items.length&&<div className="rounded-[2rem] border border-dashed border-[#17364d]/10 p-10 text-sm opacity-50">Community signals will appear as people, organizations, and connected sources contribute activity.</div>}</section><aside className="space-y-4"><Link href="/market" className="block rounded-[2rem] bg-[#17364d] p-7 text-white"><Users/><h2 className="mt-5 text-2xl font-light">People Market</h2><p className="mt-2 text-sm leading-6 opacity-60">Turn a signal into a person, capability, offering, or opportunity.</p></Link><Link href="/hey-neighbor" className="block rounded-[2rem] bg-white p-7"><HeartHandshake/><h2 className="mt-5 text-2xl font-light">Hey Neighbor</h2><p className="mt-2 text-sm leading-6 opacity-55">Turn a community need into a local response.</p></Link></aside></div></div>
}
